apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lumina.fullname" . }}-secret
  labels:
    {{- include "lumina.labels" . | nindent 4 }}
type: Opaque
data:
  NEXTAUTH_SECRET: {{ .Values.config.nextauth.secret | b64enc | quote }}
---
{{- if and .Values.externalDatabase.enabled (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lumina.fullname" . }}-db-secret
  labels:
    {{- include "lumina.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }} 